// <auto-generated />
using System;
using GestionSubterraneoWebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GestionSubterraneoWebApi.Migrations
{
    [DbContext(typeof(RegistroIncidenteDbContext))]
    partial class RegistroIncidenteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GestionSubterraneoWebApi.Modelos.RegistroIncidente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FK_Registros_CausaIncidente_IdCausa")
                        .HasColumnType("int");

                    b.Property<int>("FK_Registros_EfectoIncidente_IdEfecto")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaConsultado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FK_Registros_CausaIncidente_IdCausa");

                    b.HasIndex("FK_Registros_EfectoIncidente_IdEfecto");

                    b.ToTable("Registros");
                });

            modelBuilder.Entity("Modelos.Base_de_datos.Causa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegistrosId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CausaIncidente");
                });

            modelBuilder.Entity("Modelos.Base_de_datos.Efecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegistrosId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EfectoIncidente");
                });

            modelBuilder.Entity("GestionSubterraneoWebApi.Modelos.RegistroIncidente", b =>
                {
                    b.HasOne("Modelos.Base_de_datos.Causa", "Causa")
                        .WithMany()
                        .HasForeignKey("FK_Registros_CausaIncidente_IdCausa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelos.Base_de_datos.Efecto", "Efecto")
                        .WithMany()
                        .HasForeignKey("FK_Registros_EfectoIncidente_IdEfecto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Causa");

                    b.Navigation("Efecto");
                });
#pragma warning restore 612, 618
        }
    }
}
